[project]
name = "tars"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "anthropic>=0.79.0",
]

[project.scripts]
tars = "tars.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
